// src/views/Registry.vue
<template>
  <div class="registry-page">
    <!-- 左侧项目列表 -->
    <div class="project-panel">
      <div class="panel-header">
        <span class="panel-title">📦 项目</span>
        <button class="btn-refresh" @click="loadProjects" title="刷新">↻</button>
      </div>
      <div v-if="loadingProjects" class="loading-tip">加载中...</div>
      <div v-else class="project-list">
        <div
          v-for="p in projects"
          :key="p.name"
          :class="['project-item', { active: selectedProject === p.name }]"
          @click="selectProject(p)"
        >
          <span class="project-icon">{{ p.is_own_project ? '👤' : '🌐' }}</span>
          <span class="project-name">{{ p.name }}</span>
          <div class="project-badges">
            <span v-if="p.is_own_project" class="badge-private">私有</span>
            <span v-else class="badge-public">公开</span>
            <span class="project-count">{{ p.repo_count || p.repository_count || 0 }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- 右侧镜像列表 -->
    <div class="repo-panel">
      <div class="panel-header">
        <div class="panel-title-group">
          <span class="panel-title">
            {{ selectedProject ? `🗂 ${selectedProject}` : '请选择项目' }}
          </span>
          <span v-if="selectedProjectMeta" :class="['access-badge', selectedProjectMeta.can_write ? 'rw' : 'ro']">
            {{ selectedProjectMeta.can_write ? '可读写' : '只读' }}
          </span>
        </div>
        <div class="header-actions">
          <input v-model="searchText" class="search-input" placeholder="搜索镜像..." />
          <button class="btn-pull" @click="showPullDialog = true">📥 使用说明</button>
        </div>
      </div>

      <div v-if="!selectedProject" class="empty-tip">
        <div class="empty-icon">🗄️</div>
        <p>从左侧选择一个项目</p>
      </div>
      <div v-else-if="loadingRepos" class="empty-tip">
        <div class="empty-icon">⏳</div>
        <p>加载中...</p>
      </div>
      <div v-else-if="filteredRepos.length === 0" class="empty-tip">
        <div class="empty-icon">📭</div>
        <p>暂无镜像</p>
      </div>
      <div v-else class="repo-grid">
        <div v-for="repo in filteredRepos" :key="repo.name" class="repo-card">
          <div class="repo-card-header">
            <span class="repo-icon">🐳</span>
            <div class="repo-info">
              <div class="repo-name">{{ shortRepoName(repo.name) }}</div>
              <div class="repo-meta">
                {{ repo.artifact_count || 0 }} 个版本
                · 更新于 {{ formatTime(repo.update_time) }}
              </div>
            </div>
          </div>
          <div class="repo-tags" v-if="repo.tags && repo.tags.length">
            <span v-for="tag in repo.tags.slice(0, 4)" :key="tag" class="tag-badge">{{ tag }}</span>
            <span v-if="repo.tags.length > 4" class="tag-more">+{{ repo.tags.length - 4 }}</span>
          </div>
          <div class="repo-actions">
            <button class="btn-sm" @click="copyPullCmd(repo.name)">📋 复制地址</button>
            <button
              v-if="selectedProjectMeta?.can_write"
              class="btn-sm danger"
              @click="confirmDelete(repo)"
            >🗑 删除</button>
          </div>
        </div>
      </div>
    </div>

    <!-- 使用镜像说明弹窗 -->
    <Teleport to="body">
      <div v-if="showPullDialog" class="modal-overlay" @click="showPullDialog = false">
        <div class="modal-box" @click.stop>
          <div class="modal-header">
            <h3>📥 如何使用镜像</h3>
            <button @click="showPullDialog = false" class="btn-close">✕</button>
          </div>
          <div class="modal-body">
            <p class="tip-text">在提交作业时选择"容器作业"，填入镜像地址即可。Slurm 通过 Pyxis/Enroot 自动拉取并运行。</p>
            <div class="code-block">
              <div class="code-label">示例 sbatch 脚本</div>
              <pre>#!/bin/bash
#SBATCH -J container_job
#SBATCH -p compute
#SBATCH -N 1
#SBATCH -c 4
#SBATCH --container-image={{ harborHost }}/library/pytorch:latest
#SBATCH --container-mounts=/home/$USER:/workspace

python /workspace/train.py</pre>
            </div>
            <div class="code-block">
              <div class="code-label">Harbor 地址</div>
              <pre>{{ harborHost || '（未配置 HARBOR_URL）' }}</pre>
            </div>
          </div>
        </div>
      </div>

      <!-- 提交容器作业弹窗已移至作业提交页面 -->
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { getApiBase } from '../utils/auth'
import { dialog } from '../utils/dialog'

const projects = ref<any[]>([])
const selectedProject = ref('')
const selectedProjectMeta = ref<any>(null)
const repos = ref<any[]>([])
const searchText = ref('')
const loadingProjects = ref(false)
const loadingRepos = ref(false)
const showPullDialog = ref(false)
const harborHost = ref('')
const userProject = ref('')
const isAdmin = ref(false)

const token = () => localStorage.getItem('token') || sessionStorage.getItem('token')

const filteredRepos = computed(() =>
  searchText.value
    ? repos.value.filter(r => r.name?.toLowerCase().includes(searchText.value.toLowerCase()))
    : repos.value
)

const loadConfig = async () => {
  try {
    const res = await fetch(`${getApiBase()}/api/registry/config`, {
      headers: { Authorization: `Bearer ${token()}` }
    })
    const data = await res.json()
    harborHost.value = (data.harbor_url || '').replace(/^https?:\/\//, '').replace(/\/$/, '')
    userProject.value = data.user_project || ''
    isAdmin.value = data.is_admin || false
  } catch { /* ignore */ }
}

const loadProjects = async () => {
  loadingProjects.value = true
  try {
    const res = await fetch(`${getApiBase()}/api/registry/projects`, {
      headers: { Authorization: `Bearer ${token()}` }
    })
    const data = await res.json()
    projects.value = data.data || []
  } catch (e: any) {
    dialog.error('加载项目失败: ' + e.message)
  } finally {
    loadingProjects.value = false
  }
}

const selectProject = async (project: any) => {
  selectedProject.value = project.name
  selectedProjectMeta.value = project
  loadingRepos.value = true
  repos.value = []
  try {
    const res = await fetch(`${getApiBase()}/api/registry/projects/${project.name}/repositories`, {
      headers: { Authorization: `Bearer ${token()}` }
    })
    const data = await res.json()
    const list: any[] = data.data || []
    // 并发加载每个 repo 的 tags
    await Promise.all(list.map(async (repo) => {
      const repoName = encodeURIComponent(shortRepoName(repo.name))
      try {
        const tr = await fetch(
          `${getApiBase()}/api/registry/projects/${project.name}/repositories/${repoName}/tags`,
          { headers: { Authorization: `Bearer ${token()}` } }
        )
        const td = await tr.json()
        repo.tags = (td.data || []).flatMap((a: any) => (a.tags || []).map((t: any) => t.name))
      } catch { repo.tags = [] }
    }))
    repos.value = list
  } catch (e: any) {
    dialog.error('加载镜像失败: ' + e.message)
  } finally {
    loadingRepos.value = false
  }
}

const shortRepoName = (fullName: string) => {
  const parts = fullName.split('/')
  return parts[parts.length - 1]
}

const formatTime = (t: string) => {
  if (!t) return '-'
  return new Date(t).toLocaleDateString('zh-CN')
}

const copyPullCmd = (repoName: string) => {
  const addr = `${harborHost.value}/${selectedProject.value}/${shortRepoName(repoName)}:latest`
  navigator.clipboard.writeText(addr)
  dialog.success('镜像地址已复制')
}

const confirmDelete = async (repo: any) => {
  const name = shortRepoName(repo.name)
  if (!await dialog.confirmDelete(name, '镜像')) return
  try {
    const res = await fetch(
      `${getApiBase()}/api/registry/projects/${selectedProject.value}/repositories/${encodeURIComponent(name)}`,
      { method: 'DELETE', headers: { Authorization: `Bearer ${token()}` } }
    )
    const data = await res.json()
    if (!res.ok) throw new Error(data.error || '删除失败')
    dialog.success('删除成功')
    selectProject(selectedProjectMeta.value)
  } catch (e: any) {
    dialog.error(e.message)
  }
}

onMounted(async () => {
  await loadConfig()
  await loadProjects()
  // 默认选中用户自己的私有项目
  const own = projects.value.find(p => p.name === userProject.value)
  if (own) selectProject(own)
})
</script>

<style scoped>
.registry-page {
  display: flex;
  gap: 1rem;
  height: 100%;
  overflow: hidden;
}

.project-panel {
  width: 200px;
  flex-shrink: 0;
  background: hsl(var(--card));
  border: 1px solid hsl(var(--border));
  border-radius: var(--radius-lg);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.repo-panel {
  flex: 1;
  min-width: 0;
  background: hsl(var(--card));
  border: 1px solid hsl(var(--border));
  border-radius: var(--radius-lg);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 14px;
  border-bottom: 1px solid hsl(var(--border));
  flex-shrink: 0;
  gap: 8px;
}

.panel-title {
  font-size: 0.85rem;
  font-weight: 600;
  color: hsl(var(--foreground));
}

.header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.search-input {
  padding: 5px 10px;
  border: 1px solid hsl(var(--border));
  border-radius: 8px;
  font-size: 0.82rem;
  background: hsl(var(--background));
  color: hsl(var(--foreground));
  outline: none;
  width: 180px;
}
.search-input:focus { border-color: hsl(var(--ring)); }

.btn-refresh {
  background: none;
  border: none;
  font-size: 1rem;
  cursor: pointer;
  color: hsl(var(--muted-foreground));
  padding: 2px 6px;
  border-radius: 4px;
}
.btn-refresh:hover { background: hsl(var(--accent)); }

.btn-pull {
  padding: 5px 12px;
  background: hsl(var(--secondary));
  border: 1px solid hsl(var(--border));
  border-radius: 8px;
  font-size: 0.8rem;
  font-weight: 500;
  cursor: pointer;
  white-space: nowrap;
  color: hsl(var(--foreground));
}
.btn-pull:hover { background: hsl(var(--accent)); }

.loading-tip, .empty-tip {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: hsl(var(--muted-foreground));
  font-size: 0.85rem;
  gap: 8px;
  padding: 2rem;
}
.empty-icon { font-size: 2.5rem; opacity: 0.4; }

.project-list {
  flex: 1;
  overflow-y: auto;
  padding: 6px;
}

.project-item {
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 7px 10px;
  border-radius: 7px;
  cursor: pointer;
  font-size: 0.82rem;
  color: hsl(var(--foreground));
  transition: background 0.15s;
}
.project-item:hover { background: hsl(var(--accent)); }
.project-item.active { background: hsl(var(--primary)); color: hsl(var(--primary-foreground)); }

.project-icon { font-size: 0.9rem; }
.project-name { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.project-badges {
  display: flex;
  align-items: center;
  gap: 4px;
  flex-shrink: 0;
}
.project-count {
  font-size: 0.7rem;
  background: hsl(var(--muted));
  color: hsl(var(--muted-foreground));
  padding: 1px 6px;
  border-radius: 10px;
}
.project-item.active .project-count {
  background: hsl(var(--primary-foreground) / 0.2);
  color: hsl(var(--primary-foreground));
}
.badge-private {
  font-size: 0.62rem;
  padding: 1px 5px;
  border-radius: 8px;
  background: rgba(239,68,68,0.12);
  color: #ef4444;
  font-weight: 600;
}
.badge-public {
  font-size: 0.62rem;
  padding: 1px 5px;
  border-radius: 8px;
  background: rgba(16,185,129,0.12);
  color: #10b981;
  font-weight: 600;
}
.project-item.active .badge-private,
.project-item.active .badge-public {
  background: hsl(var(--primary-foreground) / 0.2);
  color: hsl(var(--primary-foreground));
}

.panel-title-group {
  display: flex;
  align-items: center;
  gap: 8px;
}
.access-badge {
  font-size: 0.68rem;
  padding: 2px 8px;
  border-radius: 10px;
  font-weight: 600;
}
.access-badge.rw {
  background: rgba(59,130,246,0.1);
  color: #3b82f6;
}
.access-badge.ro {
  background: hsl(var(--muted));
  color: hsl(var(--muted-foreground));
}

.repo-grid {
  flex: 1;
  overflow-y: auto;
  padding: 12px;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 10px;
  align-content: start;
}

.repo-card {
  background: hsl(var(--background));
  border: 1px solid hsl(var(--border));
  border-radius: var(--radius-md);
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  transition: box-shadow 0.15s;
}
.repo-card:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.07); }

.repo-card-header { display: flex; align-items: flex-start; gap: 10px; }
.repo-icon { font-size: 1.5rem; line-height: 1; }
.repo-info { flex: 1; min-width: 0; }
.repo-name { font-size: 0.88rem; font-weight: 600; color: hsl(var(--foreground)); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.repo-meta { font-size: 0.72rem; color: hsl(var(--muted-foreground)); margin-top: 2px; }

.repo-tags { display: flex; flex-wrap: wrap; gap: 4px; }
.tag-badge {
  padding: 2px 8px;
  background: hsl(var(--muted));
  color: hsl(var(--muted-foreground));
  border-radius: 10px;
  font-size: 0.72rem;
  font-family: monospace;
}
.tag-more { font-size: 0.72rem; color: hsl(var(--muted-foreground)); padding: 2px 4px; }

.repo-actions { display: flex; gap: 5px; flex-wrap: wrap; }

.btn-sm {
  padding: 4px 10px;
  font-size: 0.75rem;
  background: hsl(var(--secondary));
  border: 1px solid hsl(var(--border));
  border-radius: 6px;
  cursor: pointer;
  color: hsl(var(--foreground));
  transition: background 0.15s;
  white-space: nowrap;
}
.btn-sm:hover { background: hsl(var(--accent)); }
.btn-sm.primary { background: hsl(var(--primary)); color: hsl(var(--primary-foreground)); border-color: transparent; }
.btn-sm.primary:hover { opacity: 0.9; }
.btn-sm.danger { color: #ef4444; border-color: rgba(239,68,68,0.25); }
.btn-sm.danger:hover { background: #fef2f2; }

/* Modal */
.modal-overlay {
  position: fixed; inset: 0;
  background: rgba(0,0,0,0.5);
  display: flex; align-items: center; justify-content: center;
  z-index: 9999; padding: 1.5rem;
}
.modal-box {
  background: hsl(var(--card));
  border-radius: 12px;
  width: 100%; max-width: 680px;
  max-height: 85vh;
  display: flex; flex-direction: column;
  box-shadow: 0 20px 60px rgba(0,0,0,0.25);
  overflow: hidden;
}
.modal-header {
  display: flex; justify-content: space-between; align-items: center;
  padding: 14px 18px;
  border-bottom: 1px solid hsl(var(--border));
}
.modal-header h3 { margin: 0; font-size: 1rem; font-weight: 600; }
.btn-close {
  background: none; border: none; font-size: 1rem;
  color: hsl(var(--muted-foreground)); cursor: pointer;
  padding: 4px 8px; border-radius: 4px;
}
.btn-close:hover { background: hsl(var(--accent)); }
.modal-body { padding: 18px; overflow-y: auto; flex: 1; }

.tip-text { font-size: 0.85rem; color: hsl(var(--muted-foreground)); margin-bottom: 14px; }
.code-block { margin-bottom: 14px; }
.code-label { font-size: 0.72rem; font-weight: 600; color: hsl(var(--muted-foreground)); text-transform: uppercase; margin-bottom: 6px; }
.code-block pre {
  background: #1e293b; color: #e2e8f0;
  padding: 12px 14px; border-radius: 8px;
  font-size: 0.82rem; line-height: 1.6;
  overflow-x: auto; margin: 0;
}
</style>

// frontend/src/pages/user/registry/index.tsx
import { useState, useEffect, useCallback } from 'react'
import {
  Card, Button, Space, Input, Tag, Modal, message as Message,
  Empty, Spin, List, Badge, Tooltip, Typography
} from 'antd'
import {
  ReloadOutlined, SearchOutlined, DatabaseOutlined, LockOutlined,
  UnlockOutlined, UserOutlined, GlobalOutlined, CopyOutlined,
  DeleteOutlined, QuestionCircleOutlined
} from '@ant-design/icons'
import axios from 'axios'
import { getUser } from '@/utils/auth'

const { Text } = Typography

interface Project {
  project_id: number
  name: string
  owner_name?: string
  public: boolean
  repo_count: number
  creation_time?: string
  update_time?: string
}

interface Repository {
  id: number
  name: string
  project_id: number
  description?: string
  pull_count: number
  artifact_count: number
  creation_time?: string
  update_time?: string
}

interface ImageTag {
  name: string
  push_time?: string
  pull_time?: string
  size?: number
}

export default function RegistryManagement() {
  const user = getUser()
  const [loading, setLoading] = useState(false)
  const [projects, setProjects] = useState<Project[]>([])
  const [selectedProject, setSelectedProject] = useState<Project | null>(null)
  const [repositories, setRepositories] = useState<Repository[]>([])
  const [loadingRepos, setLoadingRepos] = useState(false)
  const [searchText, setSearchText] = useState('')
  const [harborUrl, setHarborUrl] = useState('')

  // 加载项目列表
  const loadProjects = useCallback(async () => {
    setLoading(true)
    try {
      const res = await axios.get('/registry/projects')
      const projectList = res.data.data || []
      setProjects(projectList)
      
      // 默认选中第一个项目
      if (projectList.length > 0 && !selectedProject) {
        setSelectedProject(projectList[0])
      }
    } catch (e: any) {
      Message.error(e.response?.data?.error || '加载项目列表失败')
    } finally {
      setLoading(false)
    }
  }, [selectedProject])

  // 加载配置信息（获取Harbor URL）
  const loadHarborConfig = useCallback(async () => {
    try {
      const res = await axios.get('/registry/config')
      setHarborUrl(res.data.harbor_url || '')
    } catch (e: any) {
      console.error('加载Harbor配置失败:', e)
    }
  }, [])

  // 加载仓库列表
  const loadRepositories = useCallback(async (project: Project) => {
    if (!project) return
    
    setLoadingRepos(true)
    try {
      const res = await axios.get(`/registry/projects/${project.name}/repositories`)
      setRepositories(res.data.data || [])
    } catch (e: any) {
      Message.error(e.response?.data?.error || '加载仓库列表失败')
      setRepositories([])
    } finally {
      setLoadingRepos(false)
    }
  }, [])

  // 初始化
  useEffect(() => {
    loadProjects()
    loadHarborConfig()
  }, [loadProjects, loadHarborConfig])

  // 当选中项目变化时，加载仓库列表
  useEffect(() => {
    if (selectedProject) {
      loadRepositories(selectedProject)
    }
  }, [selectedProject, loadRepositories])

  // 格式化时间
  const formatTime = (timeStr?: string) => {
    if (!timeStr) return '-'
    const date = new Date(timeStr)
    return date.toLocaleDateString('zh-CN', { 
      year: 'numeric', 
      month: '2-digit', 
      day: '2-digit' 
    })
  }

  // 复制镜像地址
  const copyImagePath = (repoName: string) => {
    // 移除项目前缀
    const cleanName = repoName.replace(`${selectedProject?.name}/`, '')
    const imagePath = harborUrl 
      ? `${harborUrl.replace(/^https?:\/\//, '')}/${selectedProject?.name}/${cleanName}`
      : `harbor.example.com/${selectedProject?.name}/${cleanName}`
    
    // 优先使用 Clipboard API，降级到 document.execCommand
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(imagePath).then(() => {
        Message.success('镜像地址已复制')
      }).catch(() => {
        // Clipboard API失败，尝试降级方案
        fallbackCopyTextToClipboard(imagePath)
      })
    } else {
      // 浏览器不支持 Clipboard API，使用降级方案
      fallbackCopyTextToClipboard(imagePath)
    }
  }

  // 降级复制方案（兼容HTTP环境）
  const fallbackCopyTextToClipboard = (text: string) => {
    const textArea = document.createElement('textarea')
    textArea.value = text
    textArea.style.position = 'fixed'
    textArea.style.top = '-9999px'
    textArea.style.left = '-9999px'
    document.body.appendChild(textArea)
    textArea.focus()
    textArea.select()
    
    try {
      const successful = document.execCommand('copy')
      if (successful) {
        Message.success('镜像地址已复制')
      } else {
        Message.error('复制失败，请手动复制')
      }
    } catch (err) {
      Message.error('复制失败，请手动复制')
    }
    
    document.body.removeChild(textArea)
  }

  // 显示使用说明
  const showUsageGuide = () => {
    Modal.info({
      title: '📖 使用说明',
      width: 600,
      content: (
        <div style={{ lineHeight: 1.8 }}>
          <h4>如何使用容器镜像：</h4>
          <ol>
            <li>点击仓库列表中的"📋 复制地址"按钮复制镜像地址</li>
            <li>在作业提交页面选择"容器作业"</li>
            <li>粘贴镜像地址到容器镜像输入框</li>
            <li>配置资源参数并提交作业</li>
          </ol>
          <h4>项目说明：</h4>
          <ul>
            <li><strong>library</strong>: 公共基础镜像库</li>
            <li><strong>用户名</strong>: 个人私有项目</li>
            <li><strong>其他</strong>: 团队共享项目</li>
          </ul>
        </div>
      ),
    })
  }

  // 过滤仓库
  const filteredRepos = repositories.filter(r => {
    if (!searchText.trim()) return true
    return r.name.toLowerCase().includes(searchText.toLowerCase())
  })

  return (
    <div style={{ 
      display: 'flex', 
      height: '100%', 
      gap: 0,
      overflow: 'hidden'
    }}>
      {/* 左侧项目列表 */}
      <div style={{ 
        width: 240, 
        borderRight: '1px solid #f0f0f0',
        display: 'flex',
        flexDirection: 'column',
        background: '#fafafa'
      }}>
        {/* 项目列表标题 */}
        <div style={{ 
          padding: '16px',
          borderBottom: '1px solid #f0f0f0',
          background: '#fff',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <Space>
            <DatabaseOutlined style={{ fontSize: 16 }} />
            <span style={{ fontWeight: 600 }}>项目</span>
          </Space>
          <Button
            type="text"
            size="small"
            icon={<ReloadOutlined />}
            onClick={loadProjects}
            loading={loading}
          />
        </div>

        {/* 项目列表 */}
        <div style={{ flex: 1, overflow: 'auto', padding: '8px' }}>
          {loading ? (
            <div style={{ textAlign: 'center', padding: 40 }}>
              <Spin size="small" />
            </div>
          ) : (
            <List
              dataSource={projects}
              renderItem={(project) => (
                <List.Item
                  key={project.project_id}
                  onClick={() => setSelectedProject(project)}
                  style={{
                    cursor: 'pointer',
                    padding: '12px',
                    marginBottom: 4,
                    borderRadius: 6,
                    background: selectedProject?.project_id === project.project_id ? '#e6f7ff' : '#fff',
                    border: selectedProject?.project_id === project.project_id ? '1px solid #1890ff' : '1px solid #f0f0f0',
                    transition: 'all 0.2s'
                  }}
                >
                  <List.Item.Meta
                    avatar={
                      project.public ? 
                        <GlobalOutlined style={{ fontSize: 18, color: '#52c41a' }} /> : 
                        <UserOutlined style={{ fontSize: 18, color: '#1890ff' }} />
                    }
                    title={
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span style={{ fontWeight: 500 }}>{project.name}</span>
                      </div>
                    }
                    description={
                      <Space size={4}>
                        <Tag 
                          icon={project.public ? <UnlockOutlined /> : <LockOutlined />}
                          color={project.public ? 'success' : 'default'}
                          style={{ fontSize: 11 }}
                        >
                          {project.public ? '公开' : '私有'}
                        </Tag>
                        <Badge 
                          count={project.repo_count} 
                          showZero
                          style={{ backgroundColor: '#1890ff' }}
                        />
                      </Space>
                    }
                  />
                </List.Item>
              )}
            />
          )}
        </div>
      </div>

      {/* 右侧仓库列表 */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', background: '#fff' }}>
        {/* 顶部工具栏 */}
        <div style={{ 
          padding: '16px 24px',
          borderBottom: '1px solid #f0f0f0',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center'
        }}>
          <Space>
            <DatabaseOutlined style={{ fontSize: 18, color: '#1890ff' }} />
            <span style={{ fontSize: 16, fontWeight: 600 }}>
              {selectedProject?.name || '请选择项目'}
            </span>
            {selectedProject && (
              <Tag color={selectedProject.public ? 'success' : 'default'}>
                {selectedProject.public ? '公开' : '私有'}
              </Tag>
            )}
          </Space>

          <Space>
            <Input
              placeholder="搜索镜像..."
              prefix={<SearchOutlined />}
              value={searchText}
              onChange={(e) => setSearchText(e.target.value)}
              style={{ width: 220 }}
              allowClear
            />
            <Button
              icon={<ReloadOutlined />}
              onClick={() => selectedProject && loadRepositories(selectedProject)}
              loading={loadingRepos}
            >
              刷新
            </Button>
            <Button
              icon={<QuestionCircleOutlined />}
              onClick={showUsageGuide}
            >
              使用说明
            </Button>
          </Space>
        </div>

        {/* 仓库列表 */}
        <div style={{ flex: 1, overflow: 'auto', padding: '16px 24px' }}>
          {!selectedProject ? (
            <Empty
              description="请从左侧选择一个项目"
              image={Empty.PRESENTED_IMAGE_SIMPLE}
              style={{ marginTop: 80 }}
            />
          ) : loadingRepos ? (
            <div style={{ textAlign: 'center', padding: 80 }}>
              <Spin tip="加载仓库列表中..." />
            </div>
          ) : filteredRepos.length === 0 ? (
            <Empty
              description={searchText ? '没有找到匹配的仓库' : '该项目下暂无仓库'}
              image={Empty.PRESENTED_IMAGE_SIMPLE}
              style={{ marginTop: 80 }}
            />
          ) : (
            <List
              dataSource={filteredRepos}
              renderItem={(repo) => {
                const cleanName = repo.name.replace(`${selectedProject?.name}/`, '')
                const imagePath = harborUrl 
                  ? `${harborUrl.replace(/^https?:\/\//, '')}/${selectedProject?.name}/${cleanName}`
                  : `${selectedProject?.name}/${cleanName}`

                return (
                  <Card
                    size="small"
                    key={repo.id}
                    style={{ marginBottom: 16 }}
                    bodyStyle={{ padding: 16 }}
                  >
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                      <div style={{ flex: 1 }}>
                        <Space direction="vertical" size={8} style={{ width: '100%' }}>
                          {/* 仓库名称 */}
                          <Space>
                            <DatabaseOutlined style={{ fontSize: 18, color: '#52c41a' }} />
                            <Text strong style={{ fontSize: 15 }}>
                              {cleanName}
                            </Text>
                          </Space>

                          {/* 统计信息 */}
                          <Space size={16} style={{ fontSize: 12, color: '#666' }}>
                            <span>
                              <Text type="secondary">镜像数: </Text>
                              <Text strong>{repo.artifact_count}</Text>
                            </span>
                            <span>
                              <Text type="secondary">更新于: </Text>
                              <Text>{formatTime(repo.update_time)}</Text>
                            </span>
                          </Space>

                          {/* 镜像地址 */}
                          <div style={{
                            background: '#f5f5f5',
                            padding: '8px 12px',
                            borderRadius: 4,
                            fontFamily: 'monospace',
                            fontSize: 12,
                            color: '#1890ff'
                          }}>
                            {imagePath}
                          </div>
                        </Space>
                      </div>

                      {/* 操作按钮 */}
                      <Space direction="vertical" size={8} style={{ marginLeft: 16 }}>
                        <Button
                          size="small"
                          icon={<CopyOutlined />}
                          onClick={() => copyImagePath(repo.name)}
                        >
                          复制地址
                        </Button>
                        {/* 删除按钮暂时隐藏，需要管理员权限 */}
                        {/* <Button
                          size="small"
                          danger
                          icon={<DeleteOutlined />}
                        >
                          删除
                        </Button> */}
                      </Space>
                    </div>
                  </Card>
                )
              }}
            />
          )}
        </div>
      </div>
    </div>
  )
}
